[package]
name = "camd"
version = "0.1.0"
description = "Client for DVB conditional access card servers"
authors = ["Cesbo Developers Team <info@cesbo.com>"]
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/camd"
repository = "https://github.com/cesbo/camd"
keywords = ["newcamd", "dvb", "conditional-access", "cam"]
categories = ["network-programming", "multimedia::video"]
edition = "2024"

[dependencies]
des = "0.9"
md-5 = "0.10"
rand = "0.10"
tracing = "0.1"
tokio = { version = "1", features = [
    "io-util",
    "macros",
    "net",
    "rt",
    "sync",
    "time",
] }
